image: jelaniwoods/appdev2021-vanilla-rails@sha256:c6575ef52a1e5f3c8da88a6fd59439078c347302b93914bb82b80079cbe6daf0

tasks:
  - init: bin/setup
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - vortizhe.simple-ruby-erb@0.2.1:BzpDuNAqJwUkxqT2t1YIuQ==
    - CraigMaslowski.erb@0.0.1:5znDha/nn0PphUrpB9a5Nw==
    - wingrunr21.vscode-ruby@0.26.0:VakXVw0C77hAQ3U3AZTn1Q==
    - aliariff.vscode-erb-beautify@0.2.0:JPBIiJcuf3dj5jx4nE7u8Q==
    - mbessey.vscode-rufo@0.2.1:QlBwvnvHJPqtDjkgo7+OEQ==
