image: gitpod/workspace-ruby-3.2

tasks:
  - before: |
      source $(rvm 3.2.2 do rvm env --path)
      bin/setup
      .vscode/manage_extensions
ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - vortizhe.simple-ruby-erb
    - aliariff.vscode-erb-beautify
