#!/usr/bin/env ruby

extensions = [
  "k--kato.intellij-idea-keybindings",
  "kaiwood.endwise",
  "castwide.solargraph",
]

extensions.each do |extension|
  result = `code --uninstall-extension #{extension}`
  status = results.include?("successfully uninstalled") ? true : false
  puts "Uninstalled #{extension} - #{status}"
end
